from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adaccount import AdAccount
from facebook_business.adobjects.campaign import Campaign
from facebook_business.adobjects.adset import AdSet
from facebook_business.adobjects.ad import Ad
from facebook_business.adobjects.adcreative import AdCreative
from facebook_business.adobjects.adimage import AdImage
import os, smtplib, config
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def init():
    FacebookAdsApi.init(config.APP_ID, config.APP_SECRET, config.ACCESS_TOKEN)
    return AdAccount(config.AD_ACCOUNT_ID)


# ── Email ──────────────────────────────────────────────────────────────────────

def send_email(subject, html):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = os.getenv("EMAIL_FROM")
    msg["To"]      = os.getenv("EMAIL_TO")
    msg.attach(MIMEText(html, "html"))
    with smtplib.SMTP(os.getenv("SMTP_HOST"), int(os.getenv("SMTP_PORT"))) as server:
        server.starttls()
        server.login(os.getenv("EMAIL_FROM"), os.getenv("EMAIL_PASSWORD"))
        server.sendmail(os.getenv("EMAIL_FROM"), os.getenv("EMAIL_TO"), msg.as_string())
    print(f"Email sent: {subject}")


def send_setup_email(campaign_name, campaign_id, adset_name, adset_id, ad_id,
                     targeting, budget_paise, destination_url):
    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:650px;margin:auto">
    <h2 style="color:#c0392b">Mangalya Matrimony — Ad Setup Complete</h2>

    <div style="background:#27ae60;color:white;padding:15px;border-radius:6px;margin-bottom:20px">
        <b>Your ad campaign has been successfully created and is now ACTIVE!</b>
    </div>

    <table border="1" cellpadding="10" cellspacing="0" style="border-collapse:collapse;width:100%">
        <tr style="background:#f5f5f5"><td><b>Campaign</b></td><td>{campaign_name} <small style="color:#888">({campaign_id})</small></td></tr>
        <tr><td><b>Ad Set</b></td><td>{adset_name} <small style="color:#888">({adset_id})</small></td></tr>
        <tr style="background:#f5f5f5"><td><b>Ad ID</b></td><td>{ad_id}</td></tr>
        <tr><td><b>Targeting</b></td><td>{targeting}</td></tr>
        <tr style="background:#f5f5f5"><td><b>Daily Budget</b></td><td>Rs.{budget_paise//100}/day</td></tr>
        <tr><td><b>Destination URL</b></td><td>{destination_url}</td></tr>
        <tr style="background:#f5f5f5"><td><b>Optimization</b></td><td>CompleteRegistration (Signups)</td></tr>
        <tr><td><b>Status</b></td><td><span style="background:#f39c12;color:white;padding:3px 8px;border-radius:4px">PENDING REVIEW</span></td></tr>
    </table>

    <br>
    <p>You will receive another email once Meta approves your ad and it goes <b>LIVE</b>.</p>
    <p style="color:#888;font-size:12px">Auto-generated by Mangalya Ads Manager</p>
    </body></html>
    """
    send_email(f"Mangalya Ads — '{campaign_name}' Setup Complete", html)


# ── Campaigns ──────────────────────────────────────────────────────────────────

def create_campaign(name, objective="OUTCOME_TRAFFIC", status="PAUSED"):
    account = init()
    campaign = account.create_campaign(fields=[], params={
        Campaign.Field.name: name,
        Campaign.Field.objective: objective,
        Campaign.Field.status: status,
        Campaign.Field.special_ad_categories: [],
        "is_adset_budget_sharing_enabled": False,
    })
    print(f"Created campaign: {campaign['id']} — {name}")
    return campaign


def list_campaigns():
    account = init()
    campaigns = account.get_campaigns(fields=[
        Campaign.Field.id,
        Campaign.Field.name,
        Campaign.Field.status,
        Campaign.Field.objective,
    ])
    for c in campaigns:
        print(f"[{c['status']}] {c['id']} — {c['name']} ({c['objective']})")
    return campaigns


def update_campaign_status(campaign_id, status):
    campaign = Campaign(campaign_id)
    campaign.api_update(params={Campaign.Field.status: status})
    print(f"Campaign {campaign_id} set to {status}")


# ── Ad Sets ────────────────────────────────────────────────────────────────────

def create_adset(campaign_id, name, daily_budget_cents, billing_event="IMPRESSIONS",
                 optimization_goal="REACH", targeting=None, status="PAUSED",
                 bid_strategy="LOWEST_COST_WITHOUT_CAP"):
    account = init()
    if targeting is None:
        targeting = {
            "geo_locations": {"countries": ["IN"]},
            "age_min": 18,
        }
    adset = account.create_ad_set(fields=[], params={
        AdSet.Field.name: name,
        AdSet.Field.campaign_id: campaign_id,
        AdSet.Field.daily_budget: daily_budget_cents,
        AdSet.Field.billing_event: billing_event,
        AdSet.Field.optimization_goal: optimization_goal,
        AdSet.Field.targeting: targeting,
        AdSet.Field.status: status,
        AdSet.Field.bid_strategy: bid_strategy,
        AdSet.Field.promoted_object: {"page_id": "1053689994488653"},
    })
    print(f"Created ad set: {adset['id']} — {name}")
    return adset


def list_adsets(campaign_id):
    campaign = Campaign(campaign_id)
    adsets = campaign.get_ad_sets(fields=[
        AdSet.Field.id,
        AdSet.Field.name,
        AdSet.Field.status,
        AdSet.Field.daily_budget,
    ])
    for a in adsets:
        budget = int(a.get("daily_budget", 0)) / 100
        print(f"[{a['status']}] {a['id']} — {a['name']} (Rs.{budget:.2f}/day)")
    return adsets


def update_adset_budget(adset_id, daily_budget_cents):
    adset = AdSet(adset_id)
    adset.api_update(params={AdSet.Field.daily_budget: daily_budget_cents})
    print(f"Ad set {adset_id} budget updated to Rs.{daily_budget_cents/100:.2f}/day")


# ── Creatives & Ads ────────────────────────────────────────────────────────────

def upload_image(image_path):
    account = init()
    image = account.create_ad_image(params={
        AdImage.Field.filename: image_path,
    })
    image.api_get(fields=[AdImage.Field.hash])
    print(f"Uploaded image hash: {image['hash']}")
    return image["hash"]


def create_creative(name, page_id, image_hash, message, link, headline):
    account = init()
    creative = account.create_ad_creative(fields=[], params={
        AdCreative.Field.name: name,
        AdCreative.Field.object_story_spec: {
            "page_id": page_id,
            "link_data": {
                "image_hash": image_hash,
                "link": link,
                "message": message,
                "name": headline,
                "call_to_action": {
                    "type": "SIGN_UP",
                    "value": {"link": link},
                },
            },
        },
    })
    print(f"Created creative: {creative['id']} — {name}")
    return creative


def create_ad(adset_id, creative_id, name, status="PAUSED"):
    account = init()
    ad = account.create_ad(fields=[], params={
        Ad.Field.name: name,
        Ad.Field.adset_id: adset_id,
        Ad.Field.creative: {"creative_id": creative_id},
        Ad.Field.status: status,
    })
    print(f"Created ad: {ad['id']} — {name}")
    return ad


def list_ads(adset_id):
    adset = AdSet(adset_id)
    ads = adset.get_ads(fields=[
        Ad.Field.id,
        Ad.Field.name,
        Ad.Field.status,
    ])
    for a in ads:
        print(f"[{a['status']}] {a['id']} — {a['name']}")
    return ads


def update_ad_status(ad_id, status):
    ad = Ad(ad_id)
    ad.api_update(params={Ad.Field.status: status})
    print(f"Ad {ad_id} set to {status}")


def upload_video(video_path):
    """Upload a video file to Meta Ad Account. Returns video ID."""
    from facebook_business.adobjects.advideo import AdVideo
    account = init()
    video = account.create_ad_video(params={
        AdVideo.Field.name: os.path.basename(video_path),
        AdVideo.Field.filepath: video_path,
    })
    print(f"Uploaded video: {video.get('id')}")
    return video.get("id")


def create_video_creative(name, page_id, video_id, message, headline,
                          link, description=""):
    """Create an ad creative using a video instead of an image."""
    account = init()
    creative = account.create_ad_creative(fields=[], params={
        AdCreative.Field.name: name,
        AdCreative.Field.object_story_spec: {
            "page_id": page_id,
            "video_data": {
                "video_id": video_id,
                "message": message,
                "title": headline,
                "link_description": description,
                "call_to_action": {
                    "type": "SIGN_UP",
                    "value": {"link": link},
                },
            },
        },
    })
    print(f"Created video creative: {creative['id']} — {name}")
    return creative


# ── Insights / Reporting ───────────────────────────────────────────────────────

def get_campaign_insights(campaign_id, date_preset="last_7d"):
    campaign = Campaign(campaign_id)
    insights = campaign.get_insights(fields=[
        "impressions", "clicks", "spend", "ctr", "cpc", "reach", "frequency",
    ], params={"date_preset": date_preset})
    for row in insights:
        print(
            f"Impressions: {row.get('impressions')}  "
            f"Clicks: {row.get('clicks')}  "
            f"Spend: Rs.{row.get('spend')}  "
            f"CTR: {row.get('ctr')}%"
        )
    return insights


def get_account_insights(date_preset="last_7d"):
    account = init()
    insights = account.get_insights(fields=[
        "impressions", "clicks", "spend", "ctr", "cpc", "reach", "campaign_name",
    ], params={
        "date_preset": date_preset,
        "level": "campaign",
    })
    for row in insights:
        print(
            f"{row.get('campaign_name'):40s}  "
            f"Spend: Rs.{row.get('spend'):>8}  "
            f"Impressions: {row.get('impressions'):>10}  "
            f"CTR: {row.get('ctr')}%"
        )
    return insights
