"""
Sends daily Mangalya Ads performance report via email.
Run: python email_report.py
Scheduled daily at 8 AM via Windows Task Scheduler.
"""
from dotenv import load_dotenv
load_dotenv()

import os, smtplib, config
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adset import AdSet

FacebookAdsApi.init(config.APP_ID, config.APP_SECRET, config.ACCESS_TOKEN)

ADSETS = [
    {"id": "120265076173980555", "name": "mangalya-03",  "targeting": "Kerala · Female · 23-33 · Malayalam"},
    {"id": "120265076175510555", "name": "Mangalya-01", "targeting": "AP & Telangana · Female · 23-33 · Telugu"},
]

FIELDS = ["impressions", "reach", "clicks", "spend", "ctr", "cpc", "actions"]


def get_signups(actions):
    if not actions:
        return 0
    for a in actions:
        if a.get("action_type") == "complete_registration":
            return int(a.get("value", 0))
    return 0


def build_report():
    rows_html = ""
    total_spend = 0
    total_signups = 0

    for adset in ADSETS:
        rows = AdSet(adset["id"]).get_insights(
            fields=FIELDS,
            params={"date_preset": "yesterday"}
        )
        if rows:
            r = rows[0]
            spend   = float(r.get("spend", 0))
            signups = get_signups(r.get("actions"))
            cps     = f"Rs.{spend/signups:.2f}" if signups > 0 else "N/A"
            total_spend   += spend
            total_signups += signups
            rows_html += f"""
            <tr>
                <td>{adset['name']}</td>
                <td>{adset['targeting']}</td>
                <td>{r.get('impressions', 0)}</td>
                <td>{r.get('clicks', 0)}</td>
                <td>{r.get('ctr', 0)}%</td>
                <td>Rs.{spend:.2f}</td>
                <td>{signups}</td>
                <td>{cps}</td>
            </tr>"""
        else:
            rows_html += f"""
            <tr>
                <td>{adset['name']}</td>
                <td>{adset['targeting']}</td>
                <td colspan='6' style='text-align:center;color:#999'>No data yet</td>
            </tr>"""

    cps_total = f"Rs.{total_spend/total_signups:.2f}" if total_signups > 0 else "N/A"

    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333">
    <h2 style="color:#c0392b">Mangalya Matrimony — Daily Ads Report</h2>
    <p>Date: <b>Yesterday</b></p>

    <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%">
        <thead style="background:#c0392b;color:white">
            <tr>
                <th>Campaign</th>
                <th>Targeting</th>
                <th>Impressions</th>
                <th>Clicks</th>
                <th>CTR</th>
                <th>Spend</th>
                <th>Signups</th>
                <th>Cost/Signup</th>
            </tr>
        </thead>
        <tbody>{rows_html}</tbody>
        <tfoot style="background:#f5f5f5;font-weight:bold">
            <tr>
                <td colspan="5">Total</td>
                <td>Rs.{total_spend:.2f}</td>
                <td>{total_signups}</td>
                <td>{cps_total}</td>
            </tr>
        </tfoot>
    </table>

    <br>
    <p style="color:#888;font-size:12px">This report is auto-generated by Mangalya Ads Manager.</p>
    </body></html>
    """
    return html


def send_email(html):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Mangalya Ads — Daily Report"
    msg["From"]    = os.getenv("EMAIL_FROM")
    msg["To"]      = os.getenv("EMAIL_TO")
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(os.getenv("SMTP_HOST"), int(os.getenv("SMTP_PORT"))) as server:
        server.starttls()
        server.login(os.getenv("EMAIL_FROM"), os.getenv("EMAIL_PASSWORD"))
        server.sendmail(os.getenv("EMAIL_FROM"), os.getenv("EMAIL_TO"), msg.as_string())
    print("Report sent to", os.getenv("EMAIL_TO"))


if __name__ == "__main__":
    html = build_report()
    send_email(html)
