"""
Monitors ad and sends email as soon as first impressions are recorded.
Runs every 30 minutes via Task Scheduler until first impression is detected.
"""
from dotenv import load_dotenv
load_dotenv()

import os, json, smtplib, config
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adset import AdSet

FacebookAdsApi.init(config.APP_ID, config.APP_SECRET, config.ACCESS_TOKEN)

ADSET_ID   = "120265102118480555"
FLAG_FILE  = "C:/Users/ambav/meta-ads-manager/first_impression_sent.json"


def already_sent():
    try:
        with open(FLAG_FILE) as f:
            return json.load(f).get("sent", False)
    except:
        return False


def mark_sent():
    with open(FLAG_FILE, "w") as f:
        json.dump({"sent": True}, f)


def send_alert(impressions, clicks, spend, ctr):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Mangalya Ads — First Impressions Recorded!"
    msg["From"]    = os.getenv("EMAIL_FROM")
    msg["To"]      = os.getenv("EMAIL_TO")

    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto">
    <h2 style="color:#c0392b">Your Ad is Delivering!</h2>

    <div style="background:#27ae60;color:white;padding:15px;border-radius:6px;margin-bottom:20px">
        <b>First impressions recorded for Mangalya-Telugu-01!</b>
    </div>

    <table border="1" cellpadding="10" cellspacing="0" style="border-collapse:collapse;width:100%">
        <tr style="background:#f5f5f5"><td><b>Impressions</b></td><td>{impressions}</td></tr>
        <tr><td><b>Clicks</b></td><td>{clicks}</td></tr>
        <tr style="background:#f5f5f5"><td><b>CTR</b></td><td>{ctr}%</td></tr>
        <tr><td><b>Spend</b></td><td>Rs.{spend}</td></tr>
        <tr style="background:#f5f5f5"><td><b>Campaign</b></td><td>Mangalya-Telugu-01</td></tr>
        <tr><td><b>Targeting</b></td><td>AP & Telangana · Female · 23-33 · Telugu</td></tr>
    </table>

    <br>
    <p style="color:#888;font-size:12px">Auto-generated by Mangalya Ads Manager</p>
    </body></html>
    """
    msg.attach(MIMEText(html, "html"))
    with smtplib.SMTP(os.getenv("SMTP_HOST"), int(os.getenv("SMTP_PORT"))) as server:
        server.starttls()
        server.login(os.getenv("EMAIL_FROM"), os.getenv("EMAIL_PASSWORD"))
        server.sendmail(os.getenv("EMAIL_FROM"), os.getenv("EMAIL_TO"), msg.as_string())
    print("First impression alert sent!")


if __name__ == "__main__":
    if already_sent():
        print("Alert already sent. No action needed.")
    else:
        rows = AdSet(ADSET_ID).get_insights(
            fields=["impressions", "clicks", "spend", "ctr"],
            params={"date_preset": "today"}
        )
        if rows and int(rows[0].get("impressions", 0)) > 0:
            r = rows[0]
            send_alert(
                impressions = r.get("impressions", 0),
                clicks      = r.get("clicks", 0),
                spend       = r.get("spend", 0),
                ctr         = r.get("ctr", 0),
            )
            mark_sent()
        else:
            print("No impressions yet. Will check again in 30 minutes.")
